name: ghostrun
description: GhostRun - Mobile Security & Threat Analysis App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.0
  http: ^1.2.0
  file_picker: ^8.0.0+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
